### ISSUE TITLE
Create non-functional skeleton (canned) package

### ISSUE THREAD

**Issue by rpwagner** [gneezyn/globus-contents-manager#3]
Before developing the functional code, create an installable package that has fixed response from a minimal Globus ContentsManager. This can provide a directory listing and store new files as part of a Python dictionary. Doing this will ensure that all of the necessary methods for the ContentsManager are covered.

For reference, here are the [minimum methods needed](https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html#writing-a-custom-contentsmanager):

- [x] `get`
- [x] `save`
- [x] `delete_file`
- [x] `rename_file`
- [x] `file_exists`
- [x] `dir_exists`
- [x] `is_hidden`

**Comment by gneezyn** [comment]
@rpwagner 
Implemented minimum methods under [DefaultContentsManager](https://github.com/gneezyn/globus-contents-manager/blob/issues/globus_contents_manager/default_contents_manager.py) class.
